# Generated by Django 3.2 on 2022-11-29 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='ejemplares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=50, verbose_name='DNI')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.ejemplares')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.ejemplares')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('editorial', models.CharField(max_length=50, verbose_name='Editorial')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.autores')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplares',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.libros'),
        ),
        migrations.CreateModel(
            name='devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion_prestamo', models.DateField()),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.prestamos')),
            ],
        ),
    ]
